/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/file-copy/': RouteRecordInfo<'/file-copy/', '/file-copy', Record<never, never>, Record<never, never>>,
    '/file-hash': RouteRecordInfo<'/file-hash', '/file-hash', Record<never, never>, Record<never, never>>,
    '/repo-clone': RouteRecordInfo<'/repo-clone', '/repo-clone', Record<never, never>, Record<never, never>>,
    '/s3-config': RouteRecordInfo<'/s3-config', '/s3-config', Record<never, never>, Record<never, never>>,
    '/s3-sync/': RouteRecordInfo<'/s3-sync/', '/s3-sync', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/file-copy/index.vue': {
      routes: '/file-copy/'
      views: never
    }
    'src/pages/file-hash.vue': {
      routes: '/file-hash'
      views: never
    }
    'src/pages/repo-clone.vue': {
      routes: '/repo-clone'
      views: never
    }
    'src/pages/s3-config.vue': {
      routes: '/s3-config'
      views: never
    }
    'src/pages/s3-sync/index.vue': {
      routes: '/s3-sync/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
